name: Build ImmortalWrt 25.12 x86_64 OpenClash SSRPlus

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  TZ: Asia/Shanghai
  OPENWRT_BRANCH: openwrt-25.12

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Test YAML
        run: |
          echo "YAML syntax OK"
